# Generated by Django 5.0.1 on 2024-02-01 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='client_age',
        ),
        migrations.RemoveField(
            model_name='client',
            name='client_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='client_phone',
        ),
        migrations.RemoveField(
            model_name='massagesessions',
            name='customer',
        ),
        migrations.AddField(
            model_name='client',
            name='age',
            field=models.IntegerField(default=0, verbose_name='Возраст'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='name',
            field=models.CharField(default='', max_length=128, verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='phone',
            field=models.CharField(default=0, max_length=11, verbose_name='Номер телефона'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='massagesessions',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Клиент'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.jobs', verbose_name='Профессия'),
        ),
        migrations.AlterField(
            model_name='client',
            name='job_activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.jobactivity', verbose_name='Характер работы'),
        ),
        migrations.AlterField(
            model_name='jobactivity',
            name='job_activity_name',
            field=models.CharField(max_length=64, verbose_name='Характер работы'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='job_name',
            field=models.CharField(max_length=64, verbose_name='Профессия'),
        ),
        migrations.AlterField(
            model_name='massagesessions',
            name='client_symptoms',
            field=models.ManyToManyField(to='web.symptoms', verbose_name='Симптомы'),
        ),
        migrations.AlterField(
            model_name='massagesessions',
            name='massage_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.massagetypes', verbose_name='Тип массажа'),
        ),
        migrations.AlterField(
            model_name='massagesessions',
            name='session_date',
            field=models.DateField(verbose_name='Дата сеанса'),
        ),
        migrations.AlterField(
            model_name='massagesessions',
            name='session_index',
            field=models.IntegerField(verbose_name='Номер сеанса'),
        ),
        migrations.AlterField(
            model_name='massagetypes',
            name='massage_type_name',
            field=models.CharField(max_length=64, verbose_name='Тип массажа'),
        ),
        migrations.AlterField(
            model_name='symptoms',
            name='symptom_name',
            field=models.CharField(max_length=256, verbose_name='Симптом'),
        ),
    ]
