# Generated by Django 5.0.1 on 2024-02-01 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_rename_jobs_job_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_name',
            field=models.CharField(choices=[('doctor', 'Врач'), ('driver', 'Водитель'), ('cook', 'Повар'), ('office worker', 'Оффисный работник'), ('director', 'Директор'), ('jobless', 'Безработный')], max_length=64, verbose_name='Профессия'),
        ),
        migrations.AlterField(
            model_name='jobactivity',
            name='job_activity_name',
            field=models.CharField(choices=[('active', 'Постоянно в движении'), ('passive', 'Сидячая работа'), ('hybrid', 'Смешанно')], max_length=64, verbose_name='Характер работы'),
        ),
    ]
