# Generated by Django 5.0.1 on 2024-02-01 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_job_job_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='name',
        ),
        migrations.AlterField(
            model_name='client',
            name='job',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='web.job', verbose_name='Профессия'),
        ),
        migrations.AlterField(
            model_name='client',
            name='job_activity',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='web.jobactivity', verbose_name='Характер работы'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_name',
            field=models.CharField(default='jobless', max_length=64, verbose_name='Профессия'),
        ),
        migrations.AlterField(
            model_name='jobactivity',
            name='job_activity_name',
            field=models.CharField(default='passive', max_length=64, verbose_name='Характер работы'),
        ),
    ]
