# Generated by Django 5.0.1 on 2024-02-02 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_remove_client_name_alter_client_job_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='job_activity',
            field=models.CharField(choices=[('Active', 'Подвижная работа'), ('Passive', 'Сидячая работа'), ('Hybrid', 'Смешанная работа')], default='Passive', verbose_name='Характер работы'),
        ),
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=models.CharField(verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_name',
            field=models.CharField(default='безработный', max_length=64, verbose_name='Профессия'),
        ),
        migrations.DeleteModel(
            name='JobActivity',
        ),
    ]
