# Generated by Django 5.0.1 on 2024-02-06 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_client_job_activity_alter_client_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='symptom',
            old_name='symptom_name',
            new_name='name',
        ),
    ]
