# Generated by Django 5.0.1 on 2024-02-06 17:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_alter_client_age_alter_client_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='job_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='massagetype',
            old_name='massage_type_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='massagetype',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(default='00000000000', validators=[django.core.validators.RegexValidator('^\\d{11}$', message='Номер телефона должен содержать 11 цифр')], verbose_name='Номер телефона'),
        ),
    ]
