# Generated by Django 5.0.1 on 2024-02-06 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_rename_job_name_job_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='massagetype',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена'),
        ),
    ]
