# Generated by Django 5.0.1 on 2024-02-09 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_alter_massagetype_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='massagetype',
            name='description',
            field=models.CharField(default='basic description', verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
